networks:
  appnet:
    driver: bridge

volumes:
  postgres-data:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - appnet

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-events:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "unset JMX_PORT; /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"   # UI
      - "1025:1025"   # SMTP
    networks:
      - appnet

  config-server:
    build:
      context: ./ConfigServer
    image: configserver:latest
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS: file:/workspace/config-repo
      SERVER_PORT: 8888
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/workspace/config-repo:ro
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health | grep -q 'UP'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  discovery-service:
    build:
      context: ./DiscoveryService
    image: discoveryservice:latest
    container_name: discovery-service
    environment:
      SERVER_PORT: 8761
      SPRING_APPLICATION_NAME: discovery-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health | grep -q 'UP'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet

  api-gateway:
    build:
      context: ./ApiGateway
    image: apigateway:latest
    container_name: api-gateway
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: ApiGateway
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - appnet

  user-service:
    build:
      context: ./UserService
    image: userservice:latest
    container_name: user-service
    environment:
      SERVER_PORT: 8081
      SPRING_APPLICATION_NAME: user-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8081:8081"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - appnet

  notification-service:
    build:
      context: ./NotificationService
    image: notificationservice:latest
    container_name: notification-service
    environment:
      SERVER_PORT: 8082
      SPRING_APPLICATION_NAME: notification-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    ports:
      - "8082:8082"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-server:
          condition: service_healthy
      kafka:
          condition: service_healthy
      mailhog:
          condition: service_started
    networks:
      - appnet